### ISSUE TITLE
LAY_RIGHT position doesn't add left margins

### ISSUE THREAD

**Issue by codecat** [randrew/layout#11]
When using `LAY_BOTTOM` or `LAY_RIGHT` anchors for an item's behavior, it doens't subtract the "left" margin, leaving you with an invalid offset: (yellow rectangles are the margins)

![image](https://user-images.githubusercontent.com/136534/68091801-b1954a00-fe84-11e9-9030-bcd84b73f5e8.png)

Changing the code to the following fixes the problem:
```c++
case LAY_RIGHT:
    child_rect[dim] += space - child_rect[2 + dim] - child_margins[wdim] - child_margins[dim];
    break;
```

![image](https://user-images.githubusercontent.com/136534/68091826-ef926e00-fe84-11e9-99f1-f61b305c4174.png)

This *might possibly* be an issue in `lay_arrange_overlay_squeezed_range` as well, but I have not tested it.

I can do a pull request if you want.

**Comment by randrew** [comment]
Thanks for reporting this. Sorry I'm a bit busy right now -- I'll get to this in a few days.

**Comment by codecat** [comment]
Nice! Take your time, I'm in no hurry whatsoever :)

**Comment by randrew** [comment]
Can you construct a test case for this, which demonstrates it failing before the change and passing after the change? I created a branch `test` which makes it easier to run the tests on Linux.

```sh
$ ./tool build debug tests
$ build/debug/lay_tests
```

**Comment by codecat** [comment]
Sorry for the late reply. Here's 2 tests that fail:

```c
LTEST_DECLARE(anchor_margin1)
{
    lay_id root = lay_item(ctx);
    lay_set_size_xy(ctx, root, 100, 100);

    lay_id child = lay_item(ctx);
    lay_set_size_xy(ctx, child, 50, 50);
    lay_set_margins_ltrb(ctx, child, 5, 5, 0, 0);
    lay_set_behave(ctx, child, LAY_BOTTOM | LAY_RIGHT);

    lay_insert(ctx, root, child);

    lay_run_context(ctx);

    LTEST_VEC4EQ(lay_get_rect(ctx, child), 50, 50, 50, 50);
}

LTEST_DECLARE(anchor_margin2)
{
    lay_id root = lay_item(ctx);
    lay_set_size_xy(ctx, root, 100, 100);

    lay_id child = lay_item(ctx);
    lay_set_size_xy(ctx, child, 50, 50);
    lay_set_margins_ltrb(ctx, child, 5, 5, 10, 10);
    lay_set_behave(ctx, child, LAY_BOTTOM | LAY_RIGHT);

    lay_insert(ctx, root, child);

    lay_run_context(ctx);

    LTEST_VEC4EQ(lay_get_rect(ctx, child), 40, 40, 50, 50);
}
```

**Comment by randrew** [comment]
Thanks! I'll get to this in a day or two.

**Comment by randrew** [comment]
OK, I've applied this to the `test` branch.

Could you check it and see if it works for you? Also, have you found if there is an issue with `lay_arrange_overlay_squeezed_range()`? (Sorry I do not have time to test this on my own right now. My schedule is completely packed with other things, and it would take me several hours to get something up and running with visual feedback.)

**Comment by codecat** [comment]
I have not tried this yet, but I'll be able to take a look later tonight.

**Comment by randrew** [comment]
Sorry to bug again. Do you think you could try this?

**Comment by codecat** [comment]
Oh it's been a while.. hmm I think I did test this but I don't remember the results. Will have to see if I can make some time to check this out again.

**Comment by randrew** [comment]
I went ahead and merged `test` into `master`, since nobody has reported any problems with it. But I still don't know if this fixes any problems you might have found with `lay_arrange_overlay_squeezed_range()` :)

**Comment by codecat** [comment]
Just did a quick test and I think it works okay! :tada:

Thanks for pinging me again, I've been really bad at keeping up with this issue. And thank you for maintaining this project!

**Comment by randrew** [comment]
No problem, than you :)
