### ISSUE TITLE
remove item

### ISSUE THREAD

**Issue by mgood7123** [randrew/layout#13]
how do i remove an item without having to rebuild the entire context list?

**Comment by randrew** [comment]
It's not designed for that. It's a singly-linked list, so removing stuff would be slower than just rebuilding it. The reason it's not doubly-linked for easier removal is that each node takes up less space with only 1 link, and there's less work linking each item in. The library was made to be fast for immediate-mode style layout systems, where anything can change at any time.

But if you need easy removal, it's not too hard to change it to be a doubly-linked list. I've done it in the past when customizing it for a project.
