### ISSUE TITLE
Code not working as described

### ISSUE THREAD

**Issue by iacore** [randrew/layout#14]
While reading through your code, I found something that may be an error.

https://github.com/randrew/layout/blob/b0c02829df41b066c5aaedcb946498209bcb38e5/layout.h#L783-L784

From your comment, here should be `pchild->margins[dim] + rect[2 + dim] + pchild->margins[wdim]`?

Also, about the layout algorithm itself, margins are not allowed to overlap with other margins. Did I understand it correctly?

**Comment by randrew** [comment]
> From your comment, here should be pchild->margins[dim] + rect[2 + dim] + pchild->margins[wdim]?

No, I think it should be the margins for the current item. Do you have some example code that demonstrates this is wrong?

> Also, about the layout algorithm itself, margins are not allowed to overlap with other margins. Did I understand it correctly?

I'm not sure what 'overlap' means.

**Comment by iacore** [comment]
> I'm not sure what 'overlap' means.

I mean that like in CSS, margins are allowed to overlap with each other. If the left element has `margin-right: 10px` and the right has `margin-left: 10px`, the gap should be 10px, not 20px.


I read through your code, and `rect[dim]` is set in `calc_size_***` to `margins[dim]`. I did find some other problems regarding `arrange_***` using different formula.

This is my translation in Rust.
https://github.com/locriacyber/flexlayout-rs/blob/82f131c8d0bd443d4434c9f1b47bba0107ebf4ed/src/lib.rs#L424-L447

Those formulae are different in your code.
https://github.com/randrew/layout/blob/master/layout.h#L1108
https://github.com/randrew/layout/blob/master/layout.h#L1072

***
Another thing that confused me is that you treat row and column differently. I'm not quite sure why.
https://github.com/randrew/layout/blob/master/layout.h#L1157-L1170

Finally, thanks for making this wonderful library! The is the only simple 2D layout library I can find. I extended this to arbitrary dimensions in my Rust version. (line wrap not yet working) Not sure what's use for flex hypercube though.

**Comment by randrew** [comment]
> I read through your code, and rect[dim] is set in calc_size_*** to margins[dim]. I did find some other problems regarding arrange_*** using different formula.

I mean, can you show *usage code* of the layout.h library which produces incorrect results. Linking to some other implementation code isn't going to help me.

> Another thing that confused me is that you treat row and column differently. I'm not quite sure why.
https://github.com/randrew/layout/blob/master/layout.h#L1157-L1170

Is this an issue? I'm not sure what you mean.

**Comment by iacore** [comment]
I don't have any example of your library with incorrect result. I was translating it to Rust.

Those are the places that I feel unsound.

> Is this an issue? I'm not sure what you mean.

If you exchange X and Y axis, the layout result would be different. `LAYOUT_ROW` and `LAYOUT_COLUMN` aren't using the same code.
