### ISSUE TITLE
Help:how to understand this codes for LAY_HCENTER

### ISSUE THREAD

**Issue by zhouxs1023** [randrew/layout#8]
in layout.h
![360-1642103179134111](https://user-images.githubusercontent.com/905931/40662429-e5e44a1a-6388-11e8-8544-3e1e00615f7a.png)
in oui.h
switch(flags & UI_HFILL) 
		{
 			case UI_HCENTER: 
			{
				**pkid->margins[dim] += (space-pkid->size[dim])/2 - pkid->margins[wdim];**
			} 
			break;
                        ..............
        }

but I calculated pkid->margins[dim] by OUI.H code, but I found it was not in the middle.

**Comment by randrew** [comment]
`space` -- area available for child item in this dimension
`child_rect[2 + dim]` -- area of child item in this dimension
`child_margins[wdim]` -- margins on one side of the child item in this dimension
`((free space) - (size of child)) / 2 - (margins of child)`
